"""One-shot generator for p4_experiments/canonical/cohort_s2_manifest.sha256.

Computes the concatenated sha256 of every unique-paper_id S2 extraction
file resolved from cohort.json. The result is the value that
run_pipeline.py asserts at startup (with --allow-s2-drift to override).

Run from repo root:
    python tools/verify/_oneshot_phase7_cohort_manifest.py
"""
from __future__ import annotations
import datetime as _dt
import hashlib
import json
from pathlib import Path

ROOT = Path(".")
COHORT = ROOT / "p4_experiments" / "canonical" / "cohort.json"
EXTRACT_ROOT = ROOT / "p3_thematic_synthesis" / "s2_quantitative" / "output" / "extractions"
OUT = ROOT / "p4_experiments" / "canonical" / "cohort_s2_manifest.sha256"


def main() -> int:
    cohort = json.loads(COHORT.read_text(encoding="utf-8"))
    ids = sorted({L["paper_id"] for L in cohort["labels"].values()})
    hashes: list[tuple[str, str]] = []
    missing: list[str] = []
    for pid in ids:
        cands = list(EXTRACT_ROOT.rglob(f"{pid}.json"))
        if cands:
            hashes.append((pid, hashlib.sha256(cands[0].read_bytes()).hexdigest()))
        else:
            missing.append(pid)
    manifest_text = "".join(f"{pid}\t{h}\n" for pid, h in hashes)
    concat = hashlib.sha256(manifest_text.encode("utf-8")).hexdigest()
    OUT.write_text(json.dumps({
        "description": (
            "sha256 over the concatenated newline-delimited list of "
            "(paper_id<TAB>sha256) lines, sorted by paper_id, for every "
            "unique paper_id resolved from cohort.json::labels. "
            "Generated by tools/verify/_oneshot_phase7_cohort_manifest.py; "
            "asserted by run_pipeline.py at startup (override with "
            "--allow-s2-drift)."
        ),
        "paper_id_count": len(ids),
        "resolved_count": len(hashes),
        "missing_count": len(missing),
        "missing_paper_ids": missing,
        "concat_sha256": concat,
        "generated_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "generator": "tools/verify/_oneshot_phase7_cohort_manifest.py",
    }, indent=2), encoding="utf-8")
    print(f"resolved {len(hashes)}/{len(ids)} extractions; missing {len(missing)}")
    print(f"concat_sha256: {concat}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
