"""Generate INDEX_MANIFEST.md — the human-readable record of what is indexed.

Called automatically by `tools.rag.index`. Can also be run standalone:
    python -m tools.rag.manifest --dry-run
"""
from __future__ import annotations

import argparse
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from tools.rag import config, readers


def _scan_tier(tier: int):
    """Return (included_dirs, included_files, skipped_size, total_bytes)."""
    by_dir: dict[tuple[str, str], list[Path]] = defaultdict(list)
    skipped_size: list[Path] = []

    for root_rel, glob, kind in config.TIERS[tier]:
        root = (config.REPO_ROOT / root_rel).resolve()
        if not root.exists():
            continue
        for path in root.glob(glob):
            if not path.is_file():
                continue
            # Track size-skipped before exclude check
            try:
                if path.stat().st_size > config.MAX_FILE_BYTES:
                    skipped_size.append(path)
                    continue
            except OSError:
                continue
            if config.is_excluded(path):
                continue
            by_dir[(root_rel, kind)].append(path)
    return by_dir, skipped_size


def _format_size(num_bytes: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if num_bytes < 1024:
            return f"{num_bytes:.1f} {unit}"
        num_bytes /= 1024
    return f"{num_bytes:.1f} TB"


def render_manifest(chunk_counts: dict[Path, int] | None = None,
                    db_size_bytes: int | None = None) -> str:
    """Build the INDEX_MANIFEST.md content.

    `chunk_counts` is optional: if provided (during real indexing), per-file
    chunk counts will be summed. If None (dry-run), only file counts are shown.
    """
    chunk_counts = chunk_counts or {}
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    lines: list[str] = []
    lines.append("# RAG Index Manifest")
    lines.append("")
    lines.append(f"_Generated: {now}_")
    lines.append("")
    lines.append("> This file is auto-generated by `python -m tools.rag.index`.")
    lines.append("> It lists exactly which files the local RAG tool has indexed,")
    lines.append("> and which were skipped (and why). Use it to know what the tool knows.")
    lines.append("")

    grand_files = 0
    grand_chunks = 0
    grand_bytes = 0
    phase_files: dict[str, int] = defaultdict(int)
    phase_chunks: dict[str, int] = defaultdict(int)
    silo_files: dict[str, int] = defaultdict(int)
    silo_chunks: dict[str, int] = defaultdict(int)

    tier_titles = {
        1: "Tier 1 — Documentation & methodology",
        2: "Tier 2 — Pipeline outputs (synthesized findings)",
        3: "Tier 3 — Per-paper extraction JSONs",
        4: "Tier 4 — Raw source paper texts",
    }

    lines.append("## Indexed (by tier)")
    lines.append("")
    for tier in (1, 2, 3, 4):
        lines.append(f"### {tier_titles[tier]}")
        lines.append("")
        by_dir, _ = _scan_tier(tier)
        if not by_dir:
            lines.append("_(none)_")
            lines.append("")
            continue
        for (root_rel, kind), files in sorted(by_dir.items()):
            n_files = len(files)
            n_chunks = sum(chunk_counts.get(p, 0) for p in files)
            n_bytes = sum(p.stat().st_size for p in files if p.exists())
            grand_files += n_files
            grand_chunks += n_chunks
            grand_bytes += n_bytes
            for p in files:
                rel = str(p.relative_to(config.REPO_ROOT)).replace("\\", "/")
                phase_files[config.detect_phase(rel)] += 1
                phase_chunks[config.detect_phase(rel)] += chunk_counts.get(p, 0)
                silo = config.detect_silo(rel)
                if silo:
                    silo_files[silo] += 1
                    silo_chunks[silo] += chunk_counts.get(p, 0)
            chunk_str = f", {n_chunks} chunks" if chunk_counts else ""
            lines.append(
                f"- ✅ `{root_rel}` (glob `{kind}`): **{n_files} files**{chunk_str}, {_format_size(n_bytes)}"
            )
        lines.append("")

    # Skipped section
    lines.append("## Skipped")
    lines.append("")
    lines.append("**Hard-excluded path patterns** (defined in `tools/rag/config.py`):")
    for sub in config.EXCLUDE_SUBSTRINGS:
        lines.append(f"- `{sub}`")
    lines.append("")
    lines.append("**Excluded file extensions** (build artifacts, binaries):")
    lines.append("- " + ", ".join(f"`{s}`" for s in config.EXCLUDE_SUFFIXES))
    lines.append("")

    # Size-skipped (>MAX_FILE_BYTES)
    size_skipped: list[Path] = []
    for tier in (1, 2, 3, 4):
        _, skipped = _scan_tier(tier)
        size_skipped.extend(skipped)
    if size_skipped:
        lines.append(f"**Files > {config.MAX_FILE_BYTES // (1024*1024)} MB (size-excluded):**")
        for p in sorted(size_skipped):
            rel = str(p.relative_to(config.REPO_ROOT)).replace("\\", "/")
            lines.append(f"- ⚠️  `{rel}` ({_format_size(p.stat().st_size)})")
        lines.append("")

    # Counts by phase / silo
    lines.append("## Counts by phase")
    lines.append("")
    lines.append("| Phase | Files | Chunks |")
    lines.append("|---|---:|---:|")
    for phase in sorted(phase_files):
        lines.append(f"| {phase} | {phase_files[phase]} | {phase_chunks.get(phase, 0)} |")
    lines.append("")

    if silo_files:
        lines.append("## Counts by silo")
        lines.append("")
        lines.append("| Silo | Files | Chunks |")
        lines.append("|---|---:|---:|")
        for silo in sorted(silo_files):
            lines.append(f"| {silo} | {silo_files[silo]} | {silo_chunks.get(silo, 0)} |")
        lines.append("")

    # Totals
    lines.append("## Totals")
    lines.append("")
    lines.append(f"- **Files indexed**: {grand_files}")
    if chunk_counts:
        lines.append(f"- **Chunks**: {grand_chunks}")
    lines.append(f"- **Source bytes**: {_format_size(grand_bytes)}")
    if db_size_bytes is not None:
        lines.append(f"- **Vector DB size**: {_format_size(db_size_bytes)}")
    lines.append("")

    return "\n".join(lines)


def write_manifest(chunk_counts: dict[Path, int] | None = None,
                   db_size_bytes: int | None = None) -> Path:
    content = render_manifest(chunk_counts=chunk_counts, db_size_bytes=db_size_bytes)
    config.MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    config.MANIFEST_PATH.write_text(content, encoding="utf-8")
    return config.MANIFEST_PATH


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate INDEX_MANIFEST.md (no embedding).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compatibility flag (manifest generation is always non-destructive).")
    parser.parse_args()
    path = write_manifest()
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
