"""
Apply non-English exclusion to SLR screening data.

Updates all screening files consistently after the language audit
identified 9 non-English papers that should be excluded with EX-NOTEN.

Files updated:
  1. full_text_decisions.csv      - final_decision -> exclude, exclusion_reason -> EX-NOTEN
  2. full_text_screening.xlsx     - same columns updated
  3. included_for_coding.csv      - 9 rows removed
  4. screening_reviewer_A.xlsx    - notes updated where papers appear
  5. screening_reviewer_B.xlsx    - notes updated where papers appear
  6. non_english_audit.csv        - already generated by detect_non_english.py

Run from repo root:
  python p2_systematic_review/s1_slr/tools/apply_non_english_exclusions.py
"""

import csv
import os
import shutil
from datetime import datetime

import openpyxl

SCREENING_DIR = os.path.join("p2_systematic_review", "s1_slr", "03_screening")

# Definitive list from detect_non_english.py audit (April 13, 2026)
NON_ENGLISH = {
    "1c4934de7d9a": "Chinese",
    "814040fcfdb1": "Chinese",
    "8eecae794ba6": "Indonesian",
    "955dd8044889": "Portuguese",
    "aa8d930f4f4f": "Chinese",
    "ab43aaeed4af": "Spanish",
    "b8dcb2e989c2": "Indonesian",
    "cf15566d165b": "Chinese",
    "fb499d357762": "Chinese",
}

TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M")


def backup(path: str) -> str:
    """Create a timestamped backup before modifying a file."""
    bak = path + ".bak_" + datetime.now().strftime("%Y%m%d_%H%M%S")
    shutil.copy2(path, bak)
    return bak


# ── 1. Update full_text_decisions.csv ─────────────────────────────────────

def update_full_text_decisions():
    path = os.path.join(SCREENING_DIR, "full_text_decisions.csv")
    backup(path)

    with open(path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    updated = 0
    for row in rows:
        if row["paper_id"] in NON_ENGLISH:
            lang = NON_ENGLISH[row["paper_id"]]
            row["final_decision"] = "exclude"
            row["exclusion_reason"] = "EX-NOTEN"
            row["notes"] = f"Non-English ({lang}); detected in full-text language audit {TIMESTAMP}"
            updated += 1

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    included = sum(1 for r in rows if r["final_decision"] == "include")
    excluded = sum(1 for r in rows if r["final_decision"] == "exclude")
    print(f"[1] full_text_decisions.csv: updated {updated} rows")
    print(f"    Total: {len(rows)} | Included: {included} | Excluded: {excluded}")
    return included


# ── 2. Update full_text_screening.xlsx ────────────────────────────────────

def update_full_text_xlsx():
    path = os.path.join(SCREENING_DIR, "full_text_screening.xlsx")
    backup(path)

    wb = openpyxl.load_workbook(path)
    ws = wb.active

    headers = [c.value for c in ws[1]]
    pid_col = headers.index("paper_id") + 1
    dec_a_col = headers.index("decision_reviewer_A") + 1
    dec_b_col = headers.index("decision_reviewer_B") + 1
    conflict_col = headers.index("conflict") + 1
    final_col = headers.index("final_decision") + 1
    reason_col = headers.index("exclusion_reason") + 1
    notes_col = headers.index("notes") + 1

    updated = 0
    for row_idx in range(2, ws.max_row + 1):
        pid = str(ws.cell(row=row_idx, column=pid_col).value or "")
        if pid in NON_ENGLISH:
            lang = NON_ENGLISH[pid]
            ws.cell(row=row_idx, column=dec_a_col).value = "exclude"
            ws.cell(row=row_idx, column=dec_b_col).value = "exclude"
            ws.cell(row=row_idx, column=conflict_col).value = "no"
            ws.cell(row=row_idx, column=final_col).value = "exclude"
            ws.cell(row=row_idx, column=reason_col).value = "EX-NOTEN"
            ws.cell(row=row_idx, column=notes_col).value = (
                f"Non-English ({lang}); detected in full-text language audit {TIMESTAMP}"
            )
            updated += 1

    wb.save(path)
    wb.close()
    print(f"[2] full_text_screening.xlsx: updated {updated} rows")


# ── 3. Update included_for_coding.csv ─────────────────────────────────────

def update_included_for_coding():
    path = os.path.join(SCREENING_DIR, "included_for_coding.csv")
    backup(path)

    with open(path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    before = len(rows)
    rows = [r for r in rows if r["paper_id"] not in NON_ENGLISH]
    after = len(rows)

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"[3] included_for_coding.csv: removed {before - after} rows ({before} -> {after})")
    return after


# ── 4. Update reviewer Excel files (notes only) ──────────────────────────

def update_reviewer_xlsx(filename: str, pid_col_idx: int = 1, notes_col_idx: int = 9):
    """Update notes in reviewer xlsx where non-English papers appear."""
    path = os.path.join(SCREENING_DIR, filename)
    if not os.path.exists(path):
        print(f"[4] {filename}: NOT FOUND, skipping")
        return

    backup(path)
    wb = openpyxl.load_workbook(path)
    ws = wb.active

    updated = 0
    for row_idx in range(2, ws.max_row + 1):
        pid = str(ws.cell(row=row_idx, column=pid_col_idx + 1).value or "")
        if pid in NON_ENGLISH:
            lang = NON_ENGLISH[pid]
            existing_notes = ws.cell(row=row_idx, column=notes_col_idx + 1).value or ""
            new_note = f"[EX-NOTEN] Non-English ({lang}); excluded in full-text audit {TIMESTAMP}"
            if existing_notes:
                new_note = f"{existing_notes}; {new_note}"
            ws.cell(row=row_idx, column=notes_col_idx + 1).value = new_note
            updated += 1

    wb.save(path)
    wb.close()
    print(f"[4] {filename}: annotated {updated} rows")


# ── 5. Verify consistency ─────────────────────────────────────────────────

def verify_consistency(n_included_csv: int):
    """Cross-check all files for consistency."""
    print("\n── Consistency verification ──")

    # Check CSV
    with open(os.path.join(SCREENING_DIR, "full_text_decisions.csv"), "r") as f:
        ft = list(csv.DictReader(f))
    ft_inc = sum(1 for r in ft if r["final_decision"] == "include")
    ft_exc = sum(1 for r in ft if r["final_decision"] == "exclude")
    ft_noten = sum(1 for r in ft if r.get("exclusion_reason", "") == "EX-NOTEN")

    with open(os.path.join(SCREENING_DIR, "included_for_coding.csv"), "r") as f:
        inc = list(csv.DictReader(f))
    inc_count = len(inc)

    # Verify included sets match
    ft_inc_ids = set(r["paper_id"] for r in ft if r["final_decision"] == "include")
    inc_ids = set(r["paper_id"] for r in inc)

    print(f"  full_text_decisions.csv: {len(ft)} total, {ft_inc} included, {ft_exc} excluded, {ft_noten} EX-NOTEN")
    print(f"  included_for_coding.csv: {inc_count} rows")
    print(f"  CSV included == IFC rows? {ft_inc == inc_count} ({ft_inc} == {inc_count})")
    print(f"  ID sets match? {ft_inc_ids == inc_ids}")

    # Check Excel
    wb = openpyxl.load_workbook(os.path.join(SCREENING_DIR, "full_text_screening.xlsx"), read_only=True)
    ws = wb.active
    headers = [c.value for c in next(ws.iter_rows(min_row=1, max_row=1))]
    pid_idx = headers.index("paper_id")
    final_idx = headers.index("final_decision")
    reason_idx = headers.index("exclusion_reason")

    xlsx_exc_noten = 0
    xlsx_inc = 0
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[final_idx] == "exclude" and row[reason_idx] == "EX-NOTEN":
            xlsx_exc_noten += 1
        if row[final_idx] == "include":
            xlsx_inc += 1
    wb.close()

    print(f"  full_text_screening.xlsx: {xlsx_exc_noten} EX-NOTEN exclusions, {xlsx_inc} included")
    print(f"  XLSX matches CSV? {xlsx_exc_noten == ft_noten and xlsx_inc == ft_inc}")

    if ft_inc == inc_count and ft_inc_ids == inc_ids and xlsx_exc_noten == ft_noten:
        print("\n  ✓ ALL CHECKS PASSED — data is consistent across all files")
    else:
        print("\n  ✗ INCONSISTENCY DETECTED — review manually!")


# ── Main ──────────────────────────────────────────────────────────────────

def main():
    print(f"Applying non-English exclusions ({len(NON_ENGLISH)} papers)")
    print(f"Timestamp: {TIMESTAMP}")
    print(f"Papers: {', '.join(sorted(NON_ENGLISH.keys()))}")
    print()

    n_included = update_full_text_decisions()
    update_full_text_xlsx()
    n_ifc = update_included_for_coding()
    update_reviewer_xlsx("screening_reviewer_A.xlsx")
    update_reviewer_xlsx("screening_reviewer_B.xlsx")
    verify_consistency(n_included)

    print(f"\n── PRISMA flow update needed ──")
    print(f"  Full-text assessed for eligibility: 875")
    print(f"  Full-text excluded: {875 - n_included} (was 77, now {875 - n_included})")
    print(f"    of which EX-NOTEN: {len(NON_ENGLISH)}")
    print(f"  Studies included: {n_included}")


if __name__ == "__main__":
    main()
